name: CPAuctionHouse
main: de.crafterspoint.cpauctionhouse.CPAuctionHousePlugin
version: 1.0.0-SNAPSHOT
api-version: 1.13
author: CraftersPoint
softdepend:
  - Vault
commands:
  cpauctionhouse:
    description: CPAuctionHouse main command
    aliases: [cpah]
  auctionhouse:
    description: Open the auction house
    aliases: [ah, auktion]
permissions:
  cpauctionhouse.use:
    default: true
  cpauctionhouse.admin:
    default: op
  cpauctionhouse.sell:
    default: true
  cpauctionhouse.buy:
    default: true
  cpauctionhouse.cancel:
    default: true
  cpauctionhouse.collect:
    default: true
  cpauctionhouse.browse:
    default: true
  cpauctionhouse.listings:
    default: true
